#! /bin/sh
sxhkd &
$HOME/.config/bspwm/autorun.sh
$HOME/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr --listmonitors) == 'Monitors: 2
 0: +*eDP1 1366/280x768/160+0+0  eDP1
 1: +HDMI1 1440/370x900/230+1366+0  HDMI1' ]]; then
   bspc monitor eDP1 -d 1 2 3 4 5 
   bspc monitor HDMI1 -d 6 7 8 9 10
else
   bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9
fi

bspc config border_width         3 
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	        "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)

bspc rule -a Opera desktop='^1'
bspc rule -a pcmanfm desktop='^3'
bspc rule -a zoom desktop='^4'
bspc rule -a strawberry desktop='^5'
bspc rule -a vlc desktop='^6'
bspc rule -a gimp desktop='^7' state=floating follow=on
bspc rule -a inkscape desktop='^7'
bspc rule -a mplayer2 state=floating
bspc rule -a shutter state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
